# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49456d6c79282399a9d21caa4bc364f48c2a53e5bc4d369b8c55b2099ec7554da6b467c5e99dbb37b0f76240f2b037bffdf91dc49dff38b8868ee3eb05531887

test:
  secret_key_base: 014de74bcd17a94fe688d123c4dc13890a9f798003135646091f3d8af1c11bdfa2c39c395e87ec413042b308108afa26d3e61ae43931d3531095d92809f06236

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
